export const FETCH_LIST_CATEGORY = "FETCH_LIST_CATEGORY";

export const FETCH_DELETE_CATEGORY = "FETCH_DELETE_CATEGORY"

export const FETCH_EDIT_CATEGORY = "FETCH_EDIT_CATEGORY";

export const FETCH_UPDATE_CATEGORY = "FETCH_UPDATE_CATEGORY";

export const FETCH_FILTER_CATEGORY = "FETCH_FILTER_CATEGORY";

export const FETCH_SEARCH_CATEGORY = "FETCH_SEARCH_CATEGORY";

export const FETCH_SORT_CATEGORY = "FETCH_SORT_CATEGORY";

export const FETCH_TOTALPage_CATEGORY = "FETCH_TOTALPage_CATEGORY";